name: build

on: push

jobs:
  build-ubuntu:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        build-type: [Release]
        include:
          - os: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          lfs: true
          submodules: recursive

      - name: Clean build directory
        run: |
          rm -rf build
          rm -rf CMakeCache.txt
          rm -rf CMakeFiles

      - name: Install CMake
        uses: lukka/get-cmake@latest

      - name: Run vcpkg
        uses: lukka/run-vcpkg@v10
        with:
          vcpkgDirectory: "${{ github.workspace }}/docker-ci/vcpkg"
          vcpkgGitCommitId: 9dd12f8d791f6fa4e396adbebc714d51cbee2143
          vcpkgJsonGlob: "workspace/vcpkg.json"
          runVcpkgInstall: true

      - name: Build
        uses: lukka/run-cmake@v10
        with:
          cmakeListsTxtPath: "${{ github.workspace }}/CMakeLists.txt"
          configurePreset: "default"
          buildPreset: "release"
        env:
          VCPKG_BINARY_SOURCES: "clear;x-manifest,readwrite"


      - name: Test
        run: |
          cd ${{ github.workspace }}/build
          ./rapidjson_demo