name: build

on: push

jobs:
  build-ubuntu:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        build-type: [Release]
        include:
          - os: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          lfs: true
          submodules: recursive

      # - name: Run vcpkg submodules
      #   uses: lukka/run-vcpkg@v7
      #   with:
      #     vcpkgArguments: "@${{ github.workspace }}/docker-ci/workspace/vcpkg-x64-linux.txt"
      #     vcpkgDirectory: "${{ github.workspace }}/docker-ci/vcpkg"
      #     vcpkgGitCommitId: 9dd12f8d791f6fa4e396adbebc714d51cbee2143
      #     appendedCacheKey: ${{ hashFiles('docker-ci/workspace/vcpkg-x64-linux.txt') }}

      - name: Run vcpkg
        uses: lukka/run-vcpkg@v7
        with:
          vcpkgArguments: "@${{ github.workspace }}/workspace/vcpkg-x64-linux.txt"
          vcpkgDirectory: "${{ github.workspace }}/docker-ci/vcpkg"
          vcpkgGitCommitId: 9dd12f8d791f6fa4e396adbebc714d51cbee2143
          appendedCacheKey: ${{ hashFiles('workspace/vcpkg-x64-linux.txt') }}

      - name: Build
        uses: lukka/run-cmake@v3
        with:
          cmakeListsOrSettingsJson: CMakeListsTxtBasic
          cmakeListsTxtPath: "${{ github.workspace }}/CMakeLists.txt"
          useVcpkgToolchainFile: true
          buildDirectory: "${{ github.workspace }}/build"
          cmakeBuildType: "${{ matrix.build-type }}"

      - name: Test
        run: |
          cd ${{ github.workspace }}/build
          ./rapidjson_demo